version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    hostname: rabbitmq

  redis:
    container_name: redis
    image: redis:6.2-alpine
    hostname: redis

  celery_worker:
    container_name: celery_worker
    restart: on-failure
    env_file: .env
    build:
      context: ./celery_tasks
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
    command: celery -A celery_tasks worker --concurrency=1 --loglevel=INFO

  celery_cron:
    container_name: celery_cron
    restart: on-failure
    env_file: .env
    build:
      context: ./celery_cron_jobs
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - celery_worker
    command: celery -A cron_tasks worker -B --concurrency=1 --loglevel=INFO

  rest_api:
    container_name: rest_api
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: rest_api/Dockerfile
    ports:
      - 8000:8000
    command: bash -c "uvicorn rest_api.rest_application:api_app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - celery_worker

  celery_flower:
    container_name: celery_flower
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --config=flowerconfig flower
    ports:
      - 5556:5555
    depends_on:
      - rest_api
      - redis
      - rabbitmq